### ISSUE TITLE
Custom Callback if appstore is chosen

### ISSUE THREAD

**Issue by guyisra** [timseverien/deep-link.js#1]
Is it possible to run a custom callback if the appstore/google play link are chosen (if the app is not installed)

This would be helpful for deferred deep links strategies

**Comment by timseverien** [comment]
As in a JavaScript callback? You could manually add an event listener after deep-link has initialised. If that doesn’t work, you could replace the href attribute with a `javascript:my_func()` URI, which is executed last.
