### ISSUE TITLE
iOS broken

### ISSUE THREAD

**Issue by ThumbGen** [timseverien/deep-link.js#11]
Hi

Nice idea the little lib but iOS 9.2/3 broke the deep links :( Any plans to fix it?
Also UWP support for Windows Apps would be nice.

Regards,
TG

**Comment by timseverien** [comment]
I’m not sure, but I can recall bumping into this. After some research, I think I concluded iOS 9 completely removed the ability without the intention to provide a web-safe altenative. I can do some research again, but odds are this library is end of life soon :(

Unfortunately, I do not have access to a Windows Phone, leaving me unable to test anything. I completely rely on contributions for Windows Phone support. I would gladly accept pull requests.

**Comment by timseverien** [comment]
Turns out iOS removed custom schemes in favour of Universal Links: https://developer.apple.com/library/ios/documentation/General/Conceptual/AppSearch/UniversalLinks.html
