### ISSUE TITLE
Call inside a JS method?

### ISSUE THREAD

**Issue by RafaelPlantard** [timseverien/deep-link.js#12]
Like on window.open?

**Comment by timseverien** [comment]
I deliberately designed this library to be plug-n-play, so there’s no JavaScript API you can hook into. The simplest solution is to load the library when you need it.

``` js
// Load deep-link.js after 1337 seconds \o/
window.setTimeout(() => {
  const script = document.createElement('script');
  script.src = 'deep-link.js';
  document.body.appendChild(script);
}, 1337);
```

As for `window.open`, the API doesn’t accept closures, so I have no idea what you mean. If you want to inject this library to the newly created window, I don’t have the answer to that, but changes are it’s not going to work. I’m sure that is on the internet, somewhere.
