### ISSUE TITLE
Windows Phone

### ISSUE THREAD

**Issue by robsonsobral** [timseverien/deep-link.js#2]
Hi!

I just found your repository and it looks like very interesting. Except that... I'm a Windows Phone user and now I'm curious. How to support windows phone?

I found some info, but nothing I have the expertise to understand.
- [URI schemes for launching built-in apps for Windows Phone 8](https://msdn.microsoft.com/en-us/library/windows/apps/jj662937%28v=vs.105%29.aspx)
- [Auto-launching apps using file and URI associations for Windows Phone 8](https://msdn.microsoft.com/en-us/library/windows/apps/jj206987%28v=vs.105%29.aspx)
- [UriMapper Class](https://msdn.microsoft.com/library/windows/apps/system.windows.navigation.urimapper%28v=vs.105%29.aspx)

Thank you for the plugin and for the attention.

**Comment by timseverien** [comment]
I’ve added a Windows Phone Store fallback in [0.1.0](https://github.com/timseverien/deep-link.js/releases/tag/v0.1.0). A windows-specific link should look like this:

``` html
<a href="fallback.html"
   data-app-windows="scheme://action"
   data-store-windows="1234567890">
   Open in app!
</a>
```

It would be great if you could do some tests and open more issues if necessary :)
