### ISSUE TITLE
wrong user agent on Windows Phone

### ISSUE THREAD

**Issue by robsonsobral** [timseverien/deep-link.js#3]
Hi!

I'm doing some test. The `navigator.userAgent` is being wrongly detected on Windows Phone. `navigator.userAgent` is returning:

```
Mozilla/5.0 (Mobile; Windows Phone 8.1; Android 4.0; ARM; Trident/7.0; Touch; rv:11.0; IEMobile/11.0; NOKIA; Lumia 830) like iPhone OS 7_0_3 Mac OS X AppleWebkit/537 (KHTML, like Gecko) Mobile Safari/537
```

Does [it](http://blogs.msdn.com/b/eternalcoding/archive/2014/12/16/correctly-detecting-windows-phone-when-sniffing-user-agent-string.aspx) helps? It's on [github](https://github.com/deltakosh/uatools.js) too.

Thank you for your attention.

**Comment by timseverien** [comment]
Presumably it’s related to the order of matching. It tried to do so in this order:
1. Android
2. iOS
3. Windows Phone

Looking at your User Agent string, yours would probably match Android, and then ignore the other patterns. So, I put Windows Phone first. Could you give [0.1.1](https://github.com/timseverien/deep-link.js/releases/tag/v0.1.1) a go, please?

**Comment by robsonsobral** [comment]
Yeap! It's matching the right UserAnget, now!
