### ISSUE TITLE
Can't install version 0.1.1 from bower

### ISSUE THREAD

**Issue by dunkelmpl** [timseverien/deep-link.js#9]
Hi.

I have troubles trying to install version 0.1.1 using "bower install". I get 0.1.0 instead. I think following should be changed from 0.1.0 to 0.1.1:
https://github.com/timseverien/deep-link.js/blob/master/bower.json#L4

**Comment by timseverien** [comment]
Ah, good find. This probably went wrong when merging #7 and/or #8. Should work now!
